name: deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the main
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: Install the dependencies
      run: npm install
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    # - name: Test the components
    #   run: TODO implement the tests
    - name: Build the app
      run: npm run build
    # - name: Serve and test the solution
    #   run: TODO implement the test script in the package.json
    - name: Switch to the pages and commit
      run: |
        git config --global user.email "pdima.endusol@gmail.com"
        git config --global user.name "Dmitri Poznyakov [CI/CD GH Actions]"
        git fetch origin
        git checkout pages
        git add .build
        git commit -m "Build no.$(date --iso-8601=seconds)"
